home/urls.py
from django.urls import path

from home.views import contact, csv, main, notice, notification

app_name = 'home'

urlpatterns = [
    path(
        '',
        main.IndexView.as_view(),
        name='index'
    ),
    path(
        'signup_token',
        main.SignUpTokenView.as_view(),
        name='signup_token'
    ),
    path(
        'signup_token_finish',
        main.SignUpTokenFinishView.as_view(),
        name='signup_token_finish'
    ),
    path(
        'signup/<token>',
        main.SignUpView.as_view(),
        name='signup'
    ),
    path(
        'signup_finish',
        main.SignUpFinishView.as_view(),
        name='signup_finish'
    ),
    path(
        'login',
        main.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout',
        main.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'profile',
        main.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'notice',
        notice.NoticeView.as_view(),
        name='notice'
    ),
    path(
        'notice_delete/<pk>',
        notice.notice_delete,
        name='notice_delete'
    ),
    path(
        'notice_update/<pk>',
        notice.NoticeUpdateView.as_view(),
        name='notice_update'
    ),
    path(
        'contact',
        contact.ContactView.as_view(),
        name='contact'
    ),
    path(
        'contact_kind',
        contact.ContactKindView.as_view(),
        name='contact_kind'
    ),
    path(
        'contact_list/<pk>',
        contact.ContactListView.as_view(),
        name='contact_list'
    ),
    path(
        'contact_detail/<pk>',
        contact.ContactDetailView.as_view(),
        name='contact_detail'
    ),
    path(
        'notification',
        notification.NotificationView.as_view(),
        {'mode': None},
        name='notification'
    ),
    path(
        'notification/reply_to_contact/<contact_pk>',
        notification.NotificationView.as_view(),
        {'mode': 'reply_to_contact'},
        name='notification_reply_to_contact'
    ),
    path(
        'notification/all',
        notification.NotificationView.as_view(),
        {'mode': 'all'},
        name='notification_all'
    ),
    path(
        'notification_staff_list',
        notification.NotificationStaffListView.as_view(),
        name='notification_staff_list'
    ),
    path(
        'notification_staff_list/p=<page>',
        notification.NotificationStaffListView.as_view(),
        name='notification_staff_list'
    ),
    path(
        'notification_staff_detail/<pk>',
        notification.NotificationStaffDetailView.as_view(),
        name='notification_staff_detail'
    ),
    path(
        'notification_list',
        notification.NotificationListView.as_view(),
        name='notification_list'
    ),
    path(
        'notification_list/p=<page>',
        notification.NotificationListView.as_view(),
        name='notification_list'
    ),
    path(
        'notification_detail/<pk>',
        notification.NotificationDetailView.as_view(),
        name='notification_detail'
    ),
    path(
        'staff_list',
        main.StaffListView.as_view(),
        name='staff_list'
    ),
    path(
        'download_staff_vcards/<mode>',
        main.download_staff_vcards,
        name='download_staff_vcards'
    ),
    path(
        'csv_group',
        csv.CsvView.as_view(),
        {'mode': 'group'},
        name='csv_group'
    ),
    path(
        'csv_group_confirm',
        csv.CsvConfirmView.as_view(),
        {'mode': 'group'},
        name='csv_group_confirm'
    ),
    path(
        'csv_group_success',
        csv.CsvSuccessView.as_view(),
        {'mode': 'group'},
        name='csv_group_success'
    ),
    path(
        'csv_group_download',
        csv.csv_download,
        {'mode': 'group'},
        name='csv_group_download'
    ),
    path(
        'csv_contact_kind',
        csv.CsvView.as_view(),
        {'mode': 'contact_kind'},
        name='csv_contact_kind'
    ),
    path(
        'csv_contact_kind_confirm',
        csv.CsvConfirmView.as_view(),
        {'mode': 'contact_kind'},
        name='csv_contact_kind_confirm'
    ),
    path(
        'csv_contact_kind_success',
        csv.CsvSuccessView.as_view(),
        {'mode': 'contact_kind'},
        name='csv_contact_kind_success'
    ),
    path(
        'csv_contact_kind_download',
        csv.csv_download,
        {'mode': 'contact_kind'},
        name='csv_contact_kind_download'
    ),
    path(
        'csv_staff_register',
        csv.CsvView.as_view(),
        {'mode': 'staff_register'},
        name='csv_staff_register'
    ),
    path(
        'csv_staff_register_confirm',
        csv.CsvConfirmView.as_view(),
        {'mode': 'staff_register'},
        name='csv_staff_register_confirm'
    ),
    path(
        'csv_staff_register_success',
        csv.CsvSuccessView.as_view(),
        {'mode': 'staff_register'},
        name='csv_staff_register_success'
    ),
    path(
        'csv_staff_register_download',
        csv.csv_download,
        {'mode': 'staff_register'},
        name='csv_staff_register_download'
    ),
]

penguin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('period/', include('period.urls')),
    path('theme/', include('theme.urls')),
    path('admin/', admin.site.urls),
    path("select2/", include('django_select2.urls')),
]

# Media settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

period/urls.py
from django.urls import path

from period import views

app_name = 'period'

urlpatterns = [
    path(
        'list',
        views.ListView.as_view(),
        name='list'
    ),
]

theme/urls.py
from django.urls import path

from theme.views import main, staff

app_name = 'theme'

urlpatterns = [
    path(
        'submit',
        main.SubmitView.as_view(),
        name='submit'
    ),
    path(
        'first_vote',
        main.VoteView.as_view(),
        {'mode': 'first'},
        name='first_vote'
    ),
    path(
        'final_vote',
        main.VoteView.as_view(),
        {'mode': 'final'},
        name='final_vote'
    ),
    path(
        'first_vote/<int:pk>',
        main.vote,
        {'mode': 'first'},
        name='first_vote_pk'
    ),
    path(
        'final_vote/<int:pk>',
        main.vote,
        {'mode': 'final'},
        name='final_vote_pk'
    ),
    path(
        'staff/list',
        staff.ListView.as_view(),
        name='staff_list'
    ),
    path(
        'staff/detail/<int:pk>',
        staff.DetailView.as_view(),
        name='staff_detail'
    ),
    path(
        'staff/accept/<int:pk>',
        staff.accept,
        name='staff_accept'
    ),
    path(
        'staff/disaccept/<int:pk>',
        staff.disaccept,
        name='staff_disaccept'
    ),
    path(
        'staff/csv_download',
        staff.csv_download,
        name='csv_download'
    ),
    path(
        'staff/first_vote',
        staff.FirstVoteView.as_view(),
        name='staff_first_vote'
    ),
    path(
        'staff/final_vote',
        staff.FinalVoteView.as_view(),
        name='staff_final_vote'
    ),
]

period/models.py
from django.db import models


class AbstractPeriod(models.Model):
    """Period 系 model は各手続きが行える期間を定義する

    start, finish の期間内に現在時刻が含まれていれば有効
    複数インスタンスが存在する場合は、そのうちどれかに含まれていれば有効
    """
    class Meta:
        abstract = True
        ordering = ('start',)

    def __str__(self):
        return '-'.join([str(self.start), str(self.finish)])

    start = models.DateTimeField(
        verbose_name='開始日時'
    )

    finish = models.DateTimeField(
        verbose_name='終了日時'
    )


class PeriodThemeSubmit(AbstractPeriod):
    class Meta:
        verbose_name = '統一テーマ応募期間'
        verbose_name_plural = verbose_name


class PeriodThemeFirstVote(AbstractPeriod):
    class Meta:
        verbose_name = '統一テーマ予選投票期間'
        verbose_name_plural = verbose_name


class PeriodThemeFinalVote(AbstractPeriod):
    class Meta:
        verbose_name = '統一テーマ決選投票期間'
        verbose_name_plural = verbose_name

theme/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Theme(models.Model):
    """ 統一テーマ案
    """
    class Meta:
        verbose_name = '統一テーマ案'
        verbose_name_plural = verbose_name
        ordering = ('pk',)

    def __str__(self):
        return self.theme

    def first_count(self):
        """予選投票の票数を取得
        """
        return self.firstvote_set.count()

    def final_count(self):
        """決選投票の票数を取得
        """
        return self.finalvote_set.count()

    theme = models.CharField(
        verbose_name='統一テーマ',
        max_length=100,
        help_text='1 文字以上 100 文字以下で入力してください。'
    )

    description = models.TextField(
        verbose_name='趣意文',
        max_length=400,
        validators=[MinLengthValidator(100)],
        help_text='100 文字以上 400 文字以下で入力してください。'
    )

    writer = models.OneToOneField(
        'home.User',
        verbose_name='応募者',
        on_delete=models.CASCADE
    )

    create_datetime = models.DateTimeField(
        verbose_name='応募日時',
        auto_now_add=True
    )

    first_id = models.CharField(
        verbose_name='予選コード',
        help_text='受理した場合のみ入力',
        max_length=6,
        null=True, blank=True
    )

    final_id = models.CharField(
        verbose_name='決選コード',
        help_text='決選進出した場合のみ入力',
        max_length=6,
        null=True, blank=True
    )


class AbstractVoteEptid(models.Model):
    """EPTID 記録用抽象モデル

    eptid を pk とし、作成日時（作成順）をわからなくすることで匿名性を保持
    """
    class Meta:
        abstract = True
        ordering = ('eptid',)

    def __str__(self):
        return self.eptid

    eptid = models.CharField(
        verbose_name='eptid',
        max_length=400,
        primary_key=True
    )


class FirstVoteEptid(AbstractVoteEptid):
    """予選投票 EPTID 記録用のモデル
    """
    class Meta:
        verbose_name = '予選投票/EPTID'
        verbose_name_plural = verbose_name


class FinalVoteEptid(AbstractVoteEptid):
    """決選投票 EPTID 記録用のモデル
    """
    class Meta:
        verbose_name = '決選投票/EPTID'
        verbose_name_plural = verbose_name


class AbstractVote(models.Model):
    """投票先 抽象モデル
    """
    class Meta:
        abstract = True

    def __str__(self):
        return str(self.theme)

    theme = models.ForeignKey(
        'theme.Theme',
        verbose_name='統一テーマ案',
        on_delete=models.CASCADE
    )


class FirstVote(AbstractVote):
    class Meta:
        verbose_name = '予選投票/投票先'
        verbose_name_plural = verbose_name


class FinalVote(AbstractVote):
    class Meta:
        verbose_name = '決選投票/投票先'
        verbose_name_plural = verbose_name

theme/forms.py
from django import forms

from theme import models
from countable_field.widgets import CountableWidget


class SubmitForm(forms.ModelForm):
    """統一テーマ応募
    """
    class Meta:
        model = models.Theme
        fields = (
            'theme', 'description'
        )
        widgets = {
            'theme': CountableWidget(attrs={
                'data-count': 'characters',
                'data-min-count': 1,
                'data-max-count': 100,
            }),
            'description': CountableWidget(attrs={
                'data-count': 'characters',
                'data-min-count': 100,
                'data-max-count': 400,
            })
        }


class FinalAcceptForm(forms.Form):
    """決選投票に進む件数を入力する

    1 以上 受理された統一テーマ案件数
    """
    final_accept = forms.IntegerField(
        label='決選投票進出件数',
        min_value=1,
    )

period/views.py
from django.views import generic

from datetime import datetime
from penguin.mixins import StaffOnlyMixin
from period.functions import get_period_object_list


class ListView(StaffOnlyMixin, generic.TemplateView):
    """Period 系モデルの一覧や状態を表示

    スタッフのみアクセスできるが、変更ができるのはシステム管理者のみ
    """
    template_name = 'period/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 現在時刻を登録
        context['now'] = datetime.now()

        # context に情報を登録する
        context['object_list'] = get_period_object_list()

        return context

theme/views/staff.py
import csv

from django.contrib import messages
from django.contrib.auth import mixins
from django.contrib.auth.decorators import permission_required
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from theme import forms, models


class ListView(mixins.PermissionRequiredMixin, generic.TemplateView):
    """統一テーマ案一覧を表示し、受理するかどうかを選択させる
    """
    template_name = 'theme/staff_list.html'
    permission_required = 'theme.view_theme'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 統一テーマ案一覧
        context['theme_list'] = models.Theme.objects.all()

        return context


class DetailView(mixins.PermissionRequiredMixin, generic.TemplateView):
    """pk で指定した統一テーマ案の詳細を表示する
    """
    template_name = 'theme/staff_detail.html'
    permission_required = 'theme.view_theme'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 統一テーマ案
        context['theme'] = get_object_or_404(
            models.Theme, pk=self.kwargs['pk']
        )

        return context


@permission_required('theme.view_theme', raise_exception=True)
def accept(request, pk):
    """pk で指定した統一テーマ案を受理する
    """
    # テーマを指定
    theme = get_object_or_404(
        models.Theme, pk=pk
    )

    # 受理する統一テーマに仮の予選コードを与える
    theme.first_id = 'TA'
    theme.save()

    # 受理された統一テーマ案に予選コードを割り当てる
    apply_first_id()

    # message 登録
    messages.success(request, '受理しました')

    return redirect('theme:staff_list')


@permission_required('theme.view_theme', raise_exception=True)
def disaccept(request, pk):
    """pk で指定した統一テーマ案を受理取り消しする
    """
    # テーマを指定
    theme = get_object_or_404(
        models.Theme, pk=pk
    )

    # 受理取り消しする統一テーマ案の予選コードを剥奪
    theme.first_id = None
    theme.save()

    # 受理された統一テーマ案に予選コードを割り当てる
    apply_first_id()

    # message 登録
    messages.error(request, '受理取り消ししました')

    return redirect('theme:staff_list')


def apply_first_id():
    """受理された統一テーマ案に予選コードを割り当てる

    予選コードは応募順（受理順ではない）で形式は TA-000
    """
    # 受理された統一テーマ一覧
    theme_list = [
        obj for obj in models.Theme.objects.all() if obj.first_id
    ]

    # 予選コードを振り直す
    apply_id(theme_list, 'first')


@permission_required('theme.view_theme', raise_exception=True)
def csv_download(self):
    """CSV ファイルダウンロード
    統一テーマ案の CSV ファイルをダウンロードする。
    """
    # ファイルはサーバーに残さない（危なっかしいので）
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = \
        'attachment; filename="theme.csv"'

    # CSV 書き出し
    writer = csv.writer(response)

    # ヘッダー行
    writer.writerow(['統一テーマ案', '趣意文'])

    # 各データ行
    for theme in models.Theme.objects.all():
        writer.writerow([theme.theme, theme.description])

    # response を返す
    return response


class FirstVoteView(mixins.PermissionRequiredMixin, generic.FormView):
    """予選投票の結果を表示
    """
    template_name = 'theme/staff_first_vote.html'
    permission_required = 'theme.view_theme'
    form_class = forms.FinalAcceptForm
    success_url = reverse_lazy('theme:staff_first_vote')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 統一テーマ案一覧（予選票数順）
        context['theme_list'] = get_theme_list('first')
        return context

    def form_valid(self, form):
        # フォームで入力した値が受理件数を超えている場合は
        # 受理件数を指定したものとみなす
        input_data = form.cleaned_data['final_accept']
        limit_data = models.Theme.objects.filter(
            first_id__isnull=False
        ).count()
        count = input_data if input_data <= limit_data else limit_data

        # form で指定した上位 n 件を取得
        theme_list = get_theme_list('first')[:count]

        # 決選コードを一旦全削除
        for theme in models.Theme.objects.all():
            theme.final_id = None
            theme.save()

        # 決選コードを割り当てる
        apply_id(theme_list, 'final')

        # message 登録
        messages.success(self.request, '決選コードを割り当てました')

        return super().form_valid(form)


class FinalVoteView(mixins.PermissionRequiredMixin, generic.TemplateView):
    """決選投票の結果を表示
    """
    template_name = 'theme/staff_final_vote.html'
    permission_required = 'theme.view_theme'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 統一テーマ案一覧（予選票数順）
        context['theme_list'] = get_theme_list('final')

        return context


def get_theme_list(mode):
    """context['theme_list'] を取得する(票数順)
    """
    kwargs_filter = {
        '%s_id__isnull' % mode: False
    }

    kwargs_annotate = {
        '%s_count' % mode: Count('%svote' % mode)
    }

    return models.Theme.objects.filter(
        **kwargs_filter
    ).annotate(
        **kwargs_annotate
    ).order_by(
        '-%s_count' % mode
    )


def apply_id(theme_list, mode):
    """各統一テーマ案にコードを割り当てる
    """
    for count, theme in enumerate(theme_list):
        if mode == 'first':
            theme.first_id = "TA-%s" % str(count + 1).zfill(3)
        elif mode == 'final':
            theme.final_id = "TB-%s" % str(count + 1).zfill(3)
        theme.save()

theme/templates/theme/final_vote.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
統一テーマ案決選投票
{% endblock title %}

{% block header %}
統一テーマ案決選投票
{% endblock header %}

{% block contents %}
<nav class="breadcrumb mb-2 px-3">
    <a class="breadcrumb-item" href="{% url 'home:index' %}">ホーム</a>
    <span class="breadcrumb-item active">統一テーマ案決選投票</span>
</nav>

<div class="card">
    <div class="card-body">
        {% if voted %}
        <div class="alert alert-warning" role="alert">
            <p class="mb-0">既に投票が完了しています。投票ありがとうございました！あなたの推しテーマをツイートしよう！</p>
        </div>
        {% endif %}
        <div class="alert alert-primary" role="alert">
            <ul class="mb-0">
                <li>各行を選択すると趣意文を閲覧でき、投票できます。</li>
                <li>投票は 1 人 1 回までです。投票者の個人情報は記録されません。</li>
            </ul>
        </div>
        <h3>統一テーマ案一覧（受付順）</h3>
        <table class="table table-hover table-clickable">
            <thead>
                <tr>
                    <th>決選コード</th>
                    <th>統一テーマ案</th>
                    {% if voted %}
                    <th>tweet</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for theme in theme_list %}
                <tr data-href="#" data-toggle="modal" data-target="#theme-{{ theme.pk }}">
                    <th>{{ theme.final_id }}</th>
                    <td>{{ theme.theme }}</td>
                    {% if voted %}
                    <td><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
                            data-text="【決選投票】「{{ theme.theme }}」を共有しました！京大生なら誰でも統一テーマ投票に参加できます！" data-size="large"
                            data-url="{{ base_url }}{% url 'theme:final_vote' %}" data-hashtags="NF統一テーマ投票"
                            data-lang="ja" data-show-count="false">Tweet</a></td>
                    {% endif %}
                </tr>
                <!-- Modal -->
                <div class="modal fade" id="theme-{{ theme.pk }}" tabindex="-1" role="dialog"
                    aria-labelledby="modelTitleId" aria-hidden="true">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">統一テーマ案詳細</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h3>統一テーマ案</h3>
                                <p>{{ theme.theme }}</p>
                                <h3>趣意文</h3>
                                <p>{{ theme.description|linebreaksbr }}</p>
                                <p class="text-danger">投票は 1 人 1 回までで、取り消しはできません。</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">もどる</button>
                                {% if not voted %}
                                <a href="{% url 'theme:final_vote_pk' theme.pk %}" type="button"
                                    class="btn btn-primary">投票する</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock contents %}

{% block extrajs %}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
{% endblock extrajs %}

theme/templates/theme/final_vote_result.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
統一テーマ案管理 決選投票
{% endblock title %}

{% block header %}
統一テーマ案管理 決選投票
{% endblock header %}

{% block ac_theme_staff %}
active
{% endblock ac_theme_staff %}


{% block contents %}
<nav class="breadcrumb mb-2 px-3">
    <a class="breadcrumb-item" href="{% url 'home:index' %}">ホーム</a>
    <span class="breadcrumb-item active">統一テーマ案管理</span>
</nav>


<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'theme:period' %}">期間管理</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'theme:list' %}">受理</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'theme:first_vote_result' %}">予選投票</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'theme:final_vote_result' %}">決選投票</a>
    </li>
</ul>

<div class="card">
    <div class="card-body">
        <h3>統一テーマ案一覧（獲得票数順）</h3>
        <table class="table table-hover table-clickable">
            <thead>
                <tr>
                    <th>決選コード</th>
                    <th>統一テーマ案</th>
                    <th>票数</th>
                </tr>
            </thead>
            <tbody>
                {% for theme in theme_list %}
                <tr data-href="{% url 'theme:detail' theme.pk %}"{% if forloop.first %} class="table-danger"{% endif %}>
                    <th>{{ theme.final_id }}</th>
                    <td>{{ theme.theme }}</td>
                    <td>{{ theme.final_count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contents %}

theme/templates/theme/list.html
{% extends 'base.html' %}

{% block title %}
統一テーマ案管理
{% endblock title %}

{% block header %}
統一テーマ案管理 受理
{% endblock header %}

{% block ac_theme_staff %}
active
{% endblock ac_theme_staff %}


{% block contents %}
<nav class="breadcrumb mb-2 px-3">
    <a class="breadcrumb-item" href="{% url 'home:index' %}">ホーム</a>
    <span class="breadcrumb-item active">統一テーマ案管理</span>
</nav>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'theme:period' %}">期間管理</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'theme:list' %}">受理</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'theme:first_vote_result' %}">予選投票</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'theme:final_vote_result' %}">決選投票</a>
    </li>
</ul>

<div class="card">
    <div class="card-body">
        <div class="alert alert-primary" role="alert">
            <ul class="mb-0">
                <li>各行を選択すると趣意文や応募者の情報を閲覧できます。</li>
                <li>「受理」を選択すると予選コードが割り当てられ、予選投票の候補になります。</li>
                <li>受理を取り消す場合は「取消」を選択してください。</li>
            </ul>
        </div>
        <div class="row mb-2">
            <div class="col">
                <h3>統一テーマ案一覧（受付順）</h3>
            </div>
            <div class="col">
                <div class="float-right">
                    <a class="btn btn-outline-primary" href="{% url 'theme:csv_download' %}" role="button"><i
                            class="fas fa-file-csv"></i>&nbsp;CSV ファイルダウンロード(UTF-8)</a>
                </div>
            </div>
        </div>
        <table class="table table-hover table-clickable">
            <thead>
                <tr>
                    <th>予選コード</th>
                    <th>統一テーマ</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for theme in theme_list %}
                <tr data-href="{% url 'theme:detail' theme.pk %}">
                    <th{% if theme.first_id %} class="table-success" {% endif %}>
                        {% if theme.first_id %}{{ theme.first_id }}{% else %}保留{% endif %}</th>
                        <td>{{ theme.theme }}</td>
                        <td>
                            {% if theme.first_id %}
                            <a class="btn btn-danger" href="{% url 'theme:disaccept' theme.pk %}" role="button">取消</a>
                            {% else %}
                            <a class="btn btn-success" href="{% url 'theme:accept' theme.pk %}" role="button">受理</a>
                            {% endif %}
                        </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contents %}

theme/templates/theme/staff_list.html
{% extends 'theme/staff_base.html' %}

{% block ac_theme_staff_list %}
active
{% endblock ac_theme_staff_list %}

{% block theme_staff_contents %}
<h2>統一テーマ案一覧（応募順）</h2>
<div class="alert alert-primary" role="alert">
    <ul class="mb-0">
        <li>各行を選択すると趣意文や応募者の情報を閲覧できます。</li>
        <li>「受理」を選択すると予選コードが割り当てられ、予選投票の候補になります。</li>
        <li>受理を取り消す場合は「取消」を選択してください。</li>
        <li>予選コードは応募順（受理順ではありません）に割り当てられます。</li>
    </ul>
</div>
<div class="row mb-4">
    <div class="offset-xl-6 col-xl-6">
        <div class="float-right">
            <a class="btn btn-outline-primary" href="{% url 'theme:csv_download' %}" role="button"><i
                    class="fas fa-file-csv"></i>&nbsp;CSV ファイルダウンロード(UTF-8)</a>
        </div>
    </div>
</div>
<table class="table table-hover table-clickable">
    <thead>
        <tr>
            <th>予選コード</th>
            <th>統一テーマ案</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for theme in theme_list %}
        <tr data-href="{% url 'theme:staff_detail' theme.pk %}">
            <th{% if theme.first_id %} class="table-success" {% endif %}>
                {% if theme.first_id %}{{ theme.first_id }}{% else %}保留{% endif %}</th>
                <td>{{ theme.theme }}</td>
                <td>
                    {% if theme.first_id %}
                    <a class="btn btn-primary" href="{% url 'theme:staff_disaccept' theme.pk %}" role="button">取消</a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'theme:staff_accept' theme.pk %}" role="button">受理</a>
                    {% endif %}
                </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock theme_staff_contents %}