home/urls.py
from django.urls import path

from home.views import contact, csv, main, notice, notification

app_name = 'home'

urlpatterns = [
    path(
        '',
        main.IndexView.as_view(),
        name='index'
    ),
    path(
        'signup_token',
        main.SignUpTokenView.as_view(),
        name='signup_token'
    ),
    path(
        'signup_token_finish',
        main.SignUpTokenFinishView.as_view(),
        name='signup_token_finish'
    ),
    path(
        'signup/<token>',
        main.SignUpView.as_view(),
        name='signup'
    ),
    path(
        'signup_finish',
        main.SignUpFinishView.as_view(),
        name='signup_finish'
    ),
    path(
        'login',
        main.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout',
        main.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'profile',
        main.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'notice',
        notice.NoticeView.as_view(),
        name='notice'
    ),
    path(
        'notice_delete/<pk>',
        notice.notice_delete,
        name='notice_delete'
    ),
    path(
        'notice_update/<pk>',
        notice.NoticeUpdateView.as_view(),
        name='notice_update'
    ),
    path(
        'contact',
        contact.ContactView.as_view(),
        name='contact'
    ),
    path(
        'contact_kind',
        contact.ContactKindView.as_view(),
        name='contact_kind'
    ),
    path(
        'contact_list/<pk>',
        contact.ContactListView.as_view(),
        name='contact_list'
    ),
    path(
        'contact_detail/<pk>',
        contact.ContactDetailView.as_view(),
        name='contact_detail'
    ),
    path(
        'notification',
        notification.NotificationView.as_view(),
        {'mode': None},
        name='notification'
    ),
    path(
        'notification/reply_to_contact/<contact_pk>',
        notification.NotificationView.as_view(),
        {'mode': 'reply_to_contact'},
        name='notification_reply_to_contact'
    ),
    path(
        'notification/all',
        notification.NotificationView.as_view(),
        {'mode': 'all'},
        name='notification_all'
    ),
    path(
        'notification_staff_list',
        notification.NotificationStaffListView.as_view(),
        name='notification_staff_list'
    ),
    path(
        'notification_staff_list/p=<page>',
        notification.NotificationStaffListView.as_view(),
        name='notification_staff_list'
    ),
    path(
        'notification_staff_detail/<pk>',
        notification.NotificationStaffDetailView.as_view(),
        name='notification_staff_detail'
    ),
    path(
        'notification_list',
        notification.NotificationListView.as_view(),
        name='notification_list'
    ),
    path(
        'notification_list/p=<page>',
        notification.NotificationListView.as_view(),
        name='notification_list'
    ),
    path(
        'notification_detail/<pk>',
        notification.NotificationDetailView.as_view(),
        name='notification_detail'
    ),
    path(
        'staff_list',
        main.StaffListView.as_view(),
        name='staff_list'
    ),
    path(
        'download_staff_vcards/<mode>',
        main.download_staff_vcards,
        name='download_staff_vcards'
    ),
    path(
        'csv_group',
        csv.CsvView.as_view(),
        {'mode': 'group'},
        name='csv_group'
    ),
    path(
        'csv_group_confirm',
        csv.CsvConfirmView.as_view(),
        {'mode': 'group'},
        name='csv_group_confirm'
    ),
    path(
        'csv_group_success',
        csv.CsvSuccessView.as_view(),
        {'mode': 'group'},
        name='csv_group_success'
    ),
    path(
        'csv_group_download',
        csv.csv_download,
        {'mode': 'group'},
        name='csv_group_download'
    ),
    path(
        'csv_contact_kind',
        csv.CsvView.as_view(),
        {'mode': 'contact_kind'},
        name='csv_contact_kind'
    ),
    path(
        'csv_contact_kind_confirm',
        csv.CsvConfirmView.as_view(),
        {'mode': 'contact_kind'},
        name='csv_contact_kind_confirm'
    ),
    path(
        'csv_contact_kind_success',
        csv.CsvSuccessView.as_view(),
        {'mode': 'contact_kind'},
        name='csv_contact_kind_success'
    ),
    path(
        'csv_contact_kind_download',
        csv.csv_download,
        {'mode': 'contact_kind'},
        name='csv_contact_kind_download'
    ),
    path(
        'csv_staff_register',
        csv.CsvView.as_view(),
        {'mode': 'staff_register'},
        name='csv_staff_register'
    ),
    path(
        'csv_staff_register_confirm',
        csv.CsvConfirmView.as_view(),
        {'mode': 'staff_register'},
        name='csv_staff_register_confirm'
    ),
    path(
        'csv_staff_register_success',
        csv.CsvSuccessView.as_view(),
        {'mode': 'staff_register'},
        name='csv_staff_register_success'
    ),
    path(
        'csv_staff_register_download',
        csv.csv_download,
        {'mode': 'staff_register'},
        name='csv_staff_register_download'
    ),
]

penguin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('period/', include('period.urls')),
    path('theme/', include('theme.urls')),
    path('admin/', admin.site.urls),
    path("select2/", include('django_select2.urls')),
]

# Media settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class User(AbstractUser):
    """ PENGUIN アカウント
    """

    # settings

    class Meta:
        verbose_name = 'PENGUIN アカウント'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.get_display_name()

    # functions

    def get_full_name(self):
        """フルネームを返す
        """
        return "".join([self.last_name, self.first_name])

    def get_display_name(self):
        """学部＋回生＋氏名を返す
        """
        return '(' + self.faculty + '/' + self.grade + ') ' \
            + self.get_full_name()

    def get_username_and_name(self):
        """氏名＋学生番号を返す
        """
        return self.get_full_name() + ' (' + self.username + ')'

    # validators

    username_validator = RegexValidator(
        regex=(r'^[0-9]{10}$'),
        message=('半角数字10桁で入力してください')
    )

    kana_validator = RegexValidator(
        regex=(r'^[ぁ-んー]+$'),
        message=('ひらがなで入力してください')
    )

    digit_validator = RegexValidator(
        regex=(r'^[0-9]+$'),
        message=('半角数字で入力してください')
    )

    # choices

    faculty_choices = (
        ('総', '総合人間学部/人間・環境学研究科'),
        ('文', '文学部/文学研究科'),
        ('教', '教育学部/教育学研究科'),
        ('法', '法学部/法学研究科'),
        ('経', '経済学部/経済学研究科'),
        ('理', '理学部/理学研究科'),
        ('医', '医学部/医学研究科'),
        ('薬', '薬学部/薬学研究科'),
        ('工', '工学部/工学研究科/情報学研究科'),
        ('農', '農学部/農学研究科'),
        ('他', 'その他学部/研究科'),
    )

    grade_choices = (
        ('B1', '学部1回生'),
        ('B2', '学部2回生'),
        ('B3', '学部3回生'),
        ('B4', '学部4回生'),
        ('B5+', '学部5回生以上'),
        ('修士', '修士課程'),
        ('博士', '博士課程'),
        ('他', 'その他'),
    )

    # fields

    username = models.CharField(
        verbose_name='学生番号',
        max_length=10,
        unique=True,
        validators=[username_validator],
        error_messages={
            'unique': ('その学生番号はすでに使用されています')
        },
        help_text='ハイフン無しの半角数字 10 桁で入力してください'
    )

    email = models.EmailField(
        verbose_name='メールアドレス',
        max_length=400,
        unique=True
    )

    last_name = models.CharField(
        verbose_name='姓',
        max_length=50
    )

    first_name = models.CharField(
        verbose_name='名',
        max_length=50
    )

    last_name_kana = models.CharField(
        verbose_name='姓（かな）',
        max_length=50,
        validators=[kana_validator]
    )

    first_name_kana = models.CharField(
        verbose_name='名（かな）',
        max_length=50,
        validators=[kana_validator]
    )

    faculty = models.CharField(
        verbose_name='学部/研究科',
        max_length=1,
        choices=faculty_choices
    )

    grade = models.CharField(
        verbose_name='学年',
        max_length=3,
        choices=grade_choices
    )

    tel = models.CharField(
        max_length=11,
        validators=[digit_validator],
        verbose_name='電話番号',
        help_text='ハイフン無しの半角数字で入力してください',
        unique=True
    )

    shib_eptid = models.CharField(
        verbose_name='EPTID',
        max_length=400,
        unique=True
    )

    shib_affiliation = models.CharField(
        verbose_name='affiliation',
        max_length=10
    )


class UserToken(models.Model):
    """ PENGUIN アカウント仮登録トークン

    トークンは 1 時間有効
    """

    # settings

    class Meta:
        verbose_name = '仮登録トークン'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.email

    # fields

    email = models.EmailField(
        verbose_name='メールアドレス',
        max_length=400
    )

    token = models.CharField(
        verbose_name='トークン',
        max_length=100
    )

    create_datetime = models.DateTimeField(
        verbose_name='仮登録日時',
        auto_now_add=True
    )

    used = models.BooleanField(
        verbose_name='使用済',
        default=False
    )


class GroupInfo(models.Model):
    """ 事務局員の部局担当情報
    """

    # settings

    class Meta:
        verbose_name = '部局担当情報'
        verbose_name_plural = verbose_name
        ordering = ('order',)

    def __str__(self):
        return self.group.name

    # fields

    group = models.OneToOneField(
        'auth.Group',
        verbose_name='authGroup',
        on_delete=models.CASCADE
    )

    email = models.EmailField(
        verbose_name='メールアドレス',
        max_length=200
    )

    slack_ch = models.CharField(
        verbose_name='slack channel',
        max_length=100
    )

    order = models.PositiveIntegerField(
        default=0
    )


class Notice(models.Model):
    """ ホーム画面に表示される「お知らせ」
    """

    # settings

    class Meta:
        verbose_name = 'お知らせ'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    # fields

    title = models.CharField(
        verbose_name='タイトル',
        max_length=30,
        help_text='30 文字以内で入力してください。'
    )

    body = models.TextField(
        verbose_name='本文',
        max_length=100,
        help_text='100 文字以内で入力してください。あまり長い文章は好ましくありません。'
    )

    writer = models.ForeignKey(
        'home.User',
        verbose_name='入力者',
        on_delete=models.SET_NULL,
        null=True
    )

    update_datetime = models.DateTimeField(
        verbose_name='最終更新日時',
        auto_now=True
    )


class Contact(models.Model):
    """お問い合わせ
    """

    # settings

    class Meta:
        verbose_name = 'お問い合わせ'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    # fields
    title = models.CharField(
        verbose_name='表題',
        max_length=100
    )

    body = models.TextField(
        verbose_name='本文',
        max_length=2000
    )

    kind = models.ForeignKey(
        'home.ContactKind',
        verbose_name='お問い合わせ種別',
        on_delete=models.CASCADE
    )

    writer = models.ForeignKey(
        'home.User',
        verbose_name='入力者',
        on_delete=models.CASCADE
    )

    create_datetime = models.DateTimeField(
        verbose_name='作成日時',
        auto_now_add=True
    )


class ContactKind(models.Model):
    """お問い合わせ種別
    """

    # settings

    class Meta:
        verbose_name = 'お問い合わせ種別'
        verbose_name_plural = verbose_name
        ordering = ('order',)

    def __str__(self):
        return self.name

    # fields

    name = models.CharField(
        verbose_name='種別名',
        max_length=100
    )

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='管轄'
    )

    order = models.PositiveIntegerField(
        default=0
    )


class Notification(models.Model):
    """通知
    """

    # settings

    class Meta:
        verbose_name = '通知'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def has_read(self, user):
        """ある User がすでに通知を呼んだかどうかを判定する

        NotificationRead がヒットするかどうかを返す
        """
        return self.notificationread_set.filter(
            user=user
        ).exists()

    # fields

    title = models.CharField(
        verbose_name='表題',
        max_length=50
    )

    body = models.TextField(
        verbose_name='本文',
        max_length=2000
    )

    to = models.ManyToManyField(
        'home.User',
        verbose_name='宛先',
        related_name='notification_to'
    )

    sender = models.ForeignKey(
        'home.User',
        verbose_name='送信者',
        on_delete=models.CASCADE,
        related_name='notification_from'
    )

    group = models.ForeignKey(
        'auth.Group',
        verbose_name='担当',
        on_delete=models.CASCADE,
        help_text='どの担当として送信するかをここで選択してください。',
    )

    create_datetime = models.DateTimeField(
        verbose_name='送信日時',
        auto_now_add=True
    )


class NotificationRead(models.Model):
    """通知既読情報
    """

    # settings

    class Meta:
        verbose_name = '通知既読'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.notification)

    # fields
    notification = models.ForeignKey(
        'home.Notification',
        verbose_name='通知',
        on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        'home.User',
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )

    create_datetime = models.DateTimeField(
        verbose_name='開封日時',
        auto_now_add=True
    )

home/views/csv.py
import csv

from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.views import generic

from home import forms
from home.views import helper_csv
from penguin import mixins


class CsvView(mixins.AdminOnlyMixin, generic.FormView):
    """CSV 処理 フォーム画面

    CSV ファイルのダウンロードとアップロードを行う。
    mode に応じたテンプレートを返すだけ。
    """

    form_class = forms.CsvForm

    def get_template_names(self):
        """template_name の代用

        リストで返す必要があるので注意
        """
        return ['home/csv_%s.html' % self.kwargs['mode']]


class CsvConfirmView(mixins.AdminOnlyMixin, generic.FormView):
    """CSV 処理 確認画面

    アップロードした CSV ファイルを読み込み、
    処理結果のプレビューを表示する。
    """
    form_class = forms.CsvForm

    def form_valid(self, form):
        # mode, csvfile を取得
        mode = self.kwargs['mode']
        csvfile = form.cleaned_data['csvfile']

        # context は確認画面の描画に必要。form をあらかじめ登録しておく。
        context = {'form': form}

        # mode ごとに必要な情報を取り出す
        if mode == 'group':
            context['valid_group_dict'], context['invalid_group_dict'] = \
                helper_csv.csv_to_object_group(csvfile)
        elif mode == 'contact_kind':
            context['contact_kind_dict'] = \
                helper_csv.csv_to_object_contact_kind(csvfile)
        elif mode == 'staff_register':
            context['valid_user_dict'], context['invalid_user_list'] = \
                helper_csv.csv_to_object_staff_register(csvfile)
        else:
            # 通常ここには到達しないはず
            raise Http404

        # 画面描画
        return render(self.request, 'home/csv_%s_confirm.html' % mode, context)

    def form_invalid(self, form):
        # ファイルに不備があった場合
        return helper_csv.file_invalid(self.request, self.kwargs['mode'])


class CsvSuccessView(mixins.AdminOnlyMixin, generic.FormView):
    """CSV 処理 完了画面

    実際に処理を行い、処理結果を表示する。
    """

    form_class = forms.CsvForm

    def form_valid(self, form):
        # mode, csvfile を取得する
        mode = self.kwargs['mode']
        csvfile = form.cleaned_data['csvfile']

        # mode に応じて実際の処理を行う
        if mode == 'group':
            context = helper_csv.success_group(csvfile)
        elif mode == 'contact_kind':
            context = helper_csv.success_contact_kind(csvfile)
        elif mode == 'staff_register':
            context = helper_csv.success_staff_register(csvfile)
        else:
            # 通常ここには到達しないはず
            raise Http404

        # 画面描画
        return render(self.request, 'home/csv_%s_success.html' % mode, context)

    def form_invalid(self, form):
        # ファイルに不備があった場合
        return helper_csv.file_invalid(self.request, self.kwargs['mode'])


def csv_download(request, mode):
    """CSV テンプレートファイルダウンロード

    CSV 処理に用いるテンプレートファイルをダウンロードさせる。
    CSV ファイルはこの場で作成し、ファイルはサーバーに残さない。
    """
    # アクセスはシステム管理者のみ
    if not request.user.is_superuser:
        raise PermissionDenied

    # ファイルはサーバーに残さない（危なっかしいので）
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = \
        'attachment; filename="%s.csv"' % mode

    # CSV 書き出し
    writer = csv.writer(response)

    # mode に応じてヘッダー行を描画
    if mode == 'group':
        writer.writerow([
            'Group.name（例：総合対応局 システム担当）',
            'GroupInfo.email（例：system@example.com）',
            'GroupInfo.slack_ch（例：st-system）'
        ])
    elif mode == 'contact_kind':
        # 部局担当リスト（管轄する部局の欄に 1 を入力する）
        # データ書き出し
        writer.writerow(
            ['ContactKind.name（例：11 月祭全般についてのお問い合わせ）']
            + helper_csv.get_group_list()
        )
    elif mode == 'staff_register':
        # データ書き出し
        writer.writerow(
            ['User.username（例：1029290000）'] + helper_csv.get_group_list()
        )
    else:
        # 通常ここには到達しない
        raise Http404

    # response を返す
    return response

home/templates/home/contact_detail.html
{% extends 'base.html' %}

{% block title %}
お問い合わせ一覧
{% endblock title %}

{% block header %}
お問い合わせ一覧
<br>{{ contact.title }}
{% endblock header %}

{% block ac_contact_admin %}
active
{% endblock ac_contact_admin %}

{% block contents %}
<nav class="breadcrumb mb-2 px-3">
    <a class="breadcrumb-item" href="{% url 'home:index' %}">ホーム</a>
    <a class="breadcrumb-item" href="{% url 'home:contact_kind' %}">{{ contact.kind.name }}</a>
    <a class="breadcrumb-item" href="{% url 'home:contact_list' contact.kind.pk %}">{{ contact.title }}</a>
    <span class="breadcrumb-item active">詳細</span>
</nav>

<div class="card">
    <div class="card-header">
        お問い合わせ詳細
    </div>
    <div class="card-body">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>種別</th>
                    <td>{{ contact.kind }}</td>
                </tr>
                <tr>
                    <th>表題</th>
                    <td>{{ contact.title }}</td>
                </tr>
                <tr>
                    <th>本文</th>
                    <td>{{ contact.body|linebreaksbr }}</td>
                </tr>
                <tr>
                    <th>送信者</th>
                    <td>{{ contact.writer }}</td>
                </tr>
                <tr>
                    <th>送信日時</th>
                    <td>{{ contact.create_datetime}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <a class="btn btn-primary btn-block" href="{% url 'home:notification_reply_to_contact' contact.pk %}"
            role="button"><i class="fa fa-bell"></i>&nbsp;通知システムで返信</a>
    </div>
</div>

<div class="card">
    <div class="card-header">
        送信者詳細
        <div class="float-right">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseWriterDetail"
                aria-expanded="false" aria-controls="collapseWriterDetail">
                展開
            </button>
        </div>
    </div>
    <div class="collapse" id="collapseWriterDetail">
        <div class="card-body">
            <h2>個人情報</h2>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>学生番号</th>
                        <td>{{ contact.writer.username }}</td>
                    </tr>
                    <tr>
                        <th>姓</th>
                        <td>{{ contact.writer.last_name }}</td>
                    </tr>
                    <tr>
                        <th>名</th>
                        <td>{{ contact.writer.first_name }}</td>
                    </tr>
                    <tr>
                        <th>姓（かな）</th>
                        <td>{{ contact.writer.last_name_kana }}</td>
                    </tr>
                    <tr>
                        <th>名（かな）</th>
                        <td>{{ contact.writer.first_name_kana }}</td>
                    </tr>
                </tbody>
            </table>

            <h2>連絡先</h2>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>メールアドレス</th>
                        <td>{{ contact.writer.email }}</td>
                    </tr>
                    <tr>
                        <th>電話番号</th>
                        <td>{{ contact.writer.tel }}</td>
                    </tr>
                </tbody>
            </table>

            <h2>所属</h2>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>所属</th>
                        <td>{{ contact.writer.get_faculty_display }}</td>
                    </tr>
                    <tr>
                        <th>学年</th>
                        <td>{{ contact.writer.get_grade_display }}</td>
                    </tr>
                    <tr>
                        <th>affiliation*</th>
                        <td>
                            {{ contact.writer.shib_affiliation }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <p><b>*affiliation</b>: Shibboleth(ECS-ID, SPS-ID) 認証により取得したあなたの属性です。
                「student」以外の場合（「faculty, staff」など）は一部機能が制限されます。</p>

            <h2>権限情報</h2>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>権限</th>
                        <td>
                            {% if contact.writer.is_superuser %}
                            <span class="badge badge-danger">ADMIN</span>&nbsp;システム管理者
                            {% elif contact.writer.is_staff %}
                            <span class="badge badge-success">STAFF</span>&nbsp;事務局員
                            {% else %}
                            <span class="badge badge-primary">NORMAL</span>&nbsp;一般京大生
                            {% endif %}
                        </td>
                    </tr>
                    {% if contact.writer.is_staff %}
                    <th>部局</th>
                    <td>
                        {% for group in contact.writer.groups.all %}
                        {{ group }}
                        {% if not forloop.last %}
                        <br>
                        {% endif %}
                        {% endfor %}
                    </td>
                    {% endif %}
                </tbody>
            </table>

            <h2>ログイン情報</h2>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>最終ログイン</th>
                        <td>{{ contact.writer.last_login }}</td>
                    </tr>
                    <tr>
                        <th>初アクセス</th>
                        <td>{{ contact.writer.date_joined }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col">
                <a class="btn btn-info btn-block" href="mailto:{{ contact.writer.email }}" role="button"><i
                        class="fas fa-envelope"></i>&nbsp;メール</a>
            </div>
            <div class="col">
                <a class="btn btn-info btn-block" href="tel:{{ contact.writer.tel }}" role="button"><i
                        class="fas fa-phone"></i>&nbsp;電話</a>
            </div>
        </div>


    </div>
</div>

{% endblock contents %}

home/templates/home/contact_kind.html
{% extends 'base.html' %}

{% block title %}
お問い合わせ種別一覧
{% endblock title %}

{% block header %}
お問い合わせ種別一覧
{% endblock header %}

{% block ac_contact_admin %}
active
{% endblock ac_contact_admin %}

{% block contents %}
<nav class="breadcrumb mb-2 px-3">
    <a class="breadcrumb-item" href="{% url 'home:index' %}">ホーム</a>
    <span class="breadcrumb-item active">お問い合わせ種別</span>
</nav>

<div class="card">
    <div class="card-header">
        お問い合わせ種別一覧
    </div>
    <div class="card-body">
        <p>
            お問い合わせの種別と管轄は次のとおりです。
            あなたが管轄するお問い合わせのみ閲覧することができます。
        </p>
        <table class="table table-hover table-clickable">
            <thead>
                <tr>
                    <th>種別</th>
                    <th>管轄</th>
                    <th>slack ch.</th>
                </tr>
            </thead>
            <tbody>
                {% for contact_kind in contact_kind_list %}
                {% if contact_kind.pk in contact_kind_accesible_pk_list %}
                <tr data-href="{% url 'home:contact_list' contact_kind.pk %}">
                    {% else %}
                <tr class="table-secondary">
                    {% endif %}
                    <td>{{ contact_kind.name }}</td>
                    <td>
                        {% for group in contact_kind.groups.all %}
                        {{ group.name }}
                        {% if not forloop.last %}
                        <br>
                        {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for group in contact_kind.groups.all %}
                        #{{ group.groupinfo.slack_ch }}
                        {% if not forloop.last %}
                        <br>
                        {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock contents %}

home/templates/home/csv_staff_register_confirm.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
[CSV] Staff 権限付与
{% endblock title %}

{% block header %}
[CSV] Staff 権限付与
{% endblock header %}

{% block ac_csv %}
active
{% endblock ac_csv %}


{% block contents %}
<nav class="breadcrumb mb-2 px-3">
    <a class="breadcrumb-item" href="{% url 'home:index' %}">ホーム</a>
    <a class="breadcrumb-item" href="{% url 'home:csv_contact_kind' %}">[CSV] Staff 権限付与</a>
    <span class="breadcrumb-item active">確認</span>
</nav>

<div class="card">
    <form action="" method="post" class="form" enctype="multipart/form-data">
        <div class="card-header">
            [CSV] Staff 権限付与 確認画面
        </div>
        <div class="card-body">
            <h2>3. 確認</h2>
            <p>下記の通り Sraff 権限を付与します。問題なければ「登録」を押してください。</p>
            <div class="alert alert-warning" role="alert">
                <ul class="mb-0">
                    <li>文字化けした場合は文字コードが UTF-8 になっているか確認してください。</li>
                </ul>
            </div>
            <h3>登録するデータ</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>User</th>
                        <td>部局担当</td>
                    </tr>
                </thead>
                <tbody>
                    {% for key, object in valid_user_dict.items %}
                    <tr>
                        <td>{{ object.user }}</td>
                        <td>
                            {% for group in object.group_list %}
                            {{ group }}&nbsp;
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <h3 class="text-danger">下記の学生番号を持つユーザーは存在しないため、無視されます</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>学生番号</th>
                    </tr>
                </thead>
                <tbody>
                    {% for username in invalid_user_list %}
                    <tr>
                        <td class="text-danger">{{ username }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="alert alert-warning" role="alert">
                お手数ですがもう一度ファイルを選択し直してください。
            </div>
            {% csrf_token %}
            {% bootstrap_form form %}
        </div>
        <div class="card-footer">
            {% buttons %}
            <button type="submit" class="btn btn-danger btn-block"
                formaction="{% url 'home:csv_staff_register_success' %}">
                登録
            </button>
            <button type="submit" class="btn btn-primary btn-block"
                formaction="{% url 'home:csv_staff_register_confirm' %}">
                再確認
            </button>
            {% endbuttons %}
        </div>
    </form>
</div>
{% endblock contents %}